# mia_environment
# to use this environment 
# - download miniconda and this file
# - open anaconda prompt and cd to the directory of this file
# - type the following commands in the prompt:
#   - conda env create -f mia_environment.yaml

# to start the software open anaconda prompt and type:
# - conda activate mia_environment
# - mianalyzer

name: mia_environment
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.7
  - opencv=4.5.1
  - scikit-image=0.18.1
  - imgaug=0.4
  - conda-forge::pyqt=5.12.3
  - conda-forge::cudatoolkit=11.3.1
  - conda-forge::cudnn=8.1.0
  - conda-forge::pillow=8.4.0
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda=11.7
  - pip
  - pip:
    - tensorflow < 2.11
    - mianalyzer
  
# for linux: in case you receive: 'GLIBCXX_3.4.xx not found',
# or 'libcudart.x.x' not found and GPU not recognized,
# run:
# export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH


  


