# mia_environment
# to use this environment 
# - download miniconda and this file
# - open anaconda prompt and cd to the directory of this file
# - type the following commands in the prompt:
#   - conda env create -f mia_environment.yaml

# to start the software open anaconda prompt and type:
# - conda activate mia_environment
# - mianalyzer

name: mia_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow-gpu # installs different tf-version on linux and windows, tested for 2.6 (win) and 2.4 (linux)
  - pyqt=5.12.3
  - opencv=4.5.1
  - scikit-image=0.18.1
  - imgaug=0.4
  - conda-forge::pillow=8.4.0
  - pip
  - pip:
    - mianalyzer

  
